### ISSUE TITLE
Delay in dashboard with displaying stuff

### ISSUE THREAD

**Issue by Huvik** [graphcool/prisma-cloud-feedback#1]
## Issues: 
After i created new cluster. it took some time to display in cloud dashboard with clusters. When i deleted service from prisma cloud, service is still displayed in dashboard. Can access it, but no data shown etc. Maybe some kind of cache? Even hard restart `Shift + CMD + R` service is still there.

**Comment by Huvik** [comment]
Same goes with creating and deleting workspaces, and in deleting workspaces you can delete workspace without name and when you write something to input delete button is disabled.

**Comment by peterschussheim** [comment]
I second this feedback.  Not sure if it is due to cache configuration but the UI interactions aren't responsive.

Clearing the browser cache does not help.

**Comment by marktani** [comment]
This should be much better by now, therefore I'm closing it 🙂
Feel free to provide more feedback in a new issue.

Thanks!
