### ISSUE TITLE
Issues with deploying: "Could not connect to cluster ..."

### ISSUE THREAD

**Issue by ForsakenHarmony** [graphcool/prisma-cloud-feedback#10]
```
> prisma deploy
 !    Could not connect to cluster prisma-aws with host https://prisma-aws.leah.prisma.sh. Did you provide the right port?

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"

```

The cluster is shown in the web interface and the service is there as well, but it failed midway through deployment and no I get that message

**Comment by marktani** [comment]
Hey @ForsakenHarmony, thanks for raising this issue.

Could it be that you deployed the service before the cluster was fully set up? 

Could you try deploying another service and see if that works?

**Comment by ForsakenHarmony** [comment]
It still does it

**Comment by marktani** [comment]
What's your `prisma version`?

**Comment by ForsakenHarmony** [comment]
```
> prisma --version
prisma/1.2.3 (windows-x64) node-v9.4.0
```

sometimes it shows `ERROR: GraphQL Error (Code: 504)` as well

**Comment by marktani** [comment]
Could you try with the latest `prisma@beta` version instead? `npm install -g prisma@beta`

**Comment by ForsakenHarmony** [comment]
Still the same

**Comment by maxdarque** [comment]
I'm getting this as well. 

Just checking my configuration is correct:

```
PRISMA_ENDPOINT="https://cluster-name.my-account-name.prisma.sh/service-name-in-prisma.yml-file/dev"
PRISMA_CLUSTER="my-account-name/cluster-name"
```

**Comment by maxdarque** [comment]
I'm no longer getting this error with the new URLs

**Comment by marktani** [comment]
Thanks @maxdarque, this should now be fixed.
