### ISSUE TITLE
Prisma Console shows an error notification

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#107]
@OniVe commented on [Mon Mar 19 2018](https://github.com/graphcool/prisma/issues/2113)

# Bug Report

**Current behavior**

The site [prisma.sh](https://app.prisma.sh) shows the notification: `GraphQL error: __typename did not match an object type: UpdateSecrets`

**Reproduction**

- Change the value of `PRISMA_SECRET` in the file "`.env`"
- Go to `https://app.prisma.sh/<slug>/services`
- Select a service from the list in which there were changes (or go to `https://app.prisma.sh/<slug>/services/prisma-eu1/<service-name>/dev/dashboard`)

**Expected behavior?**

No error notification

**Comment by marktani** [comment]
Thanks a lot for your report, @OniVe!

Did you deploy your project after you changed the secret in the first step?

**Comment by OniVe** [comment]
Order of actions:

- comand: `prisma init`
  - setup: GraphQL server/fullstack boilerplate
  - boilerplate: typescript-advance
  - cluster: `<slug>/prisma-eu1`
- Log: _Your GraphQL database endpoint is live_ (Endpoints received)
- Action: Change the value of `PRISMA_SECRET` in the file "`.env`"
- comand: `prisma deploy`
- Action: Go to Prisma Console and got error notification.

**Comment by marktani** [comment]
Thanks for elaborating that! I will look into a reproduction.
Does logging out and logging in again work as expected?

**Comment by OniVe** [comment]
Logging out and logging does not solve the problem.

**Comment by AkimaLunar** [comment]
I am getting the same error in Prisma's Dashboard...

```
prisma GraphQL error: __typename did not match an object type: UpdateSecrets
```

...after moving the secret to `.env`. I also had to disable the authentication in `prisma.yml` because I started getting:

```
[GraphQL error]: Message:  Your token is invalid. It might have expired or you might be using a token from a different project., Location: undefined, Path: undefined
```

I am using `new Prisma()` from `prisma-binding` to pass the secret.

**Comment by marktani** [comment]
This is fixed :slightly_smiling_face:
