### ISSUE TITLE
Explain differences between service and cluster

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma-cloud-feedback#11]
For the devop / docker / AWS morons like me, it's unclear what the difference is between a service and cluster and how they relate.  I have this service that I can connect to with data... but I have a cluster that's connected to my database, that also has something to do with my service.

Mah. 🤣

**Comment by nikolasburk** [comment]
That's definitely a valid point, thanks @LawJolla! Out of curiosity - did you see the [Cluster docs](https://www.prismagraphql.com/docs/reference/clusters/overview-eu2ood0she) and were they helping in any way. I'm aware they don't specifically target the _difference_ between clusters and services - but do they help you in any way understanding what clusters are? 

Otherwise, what questions do they leave open for you?

**Comment by LawJolla** [comment]
Thanks @nikolasburk !

I did.  It makes sense when reading it, but then gets murky in practice.  Let me see if I can better describe my confusion.  I suspect my problem comes from trying to shoehorn new technologies into what I already know.

Most of my backend experience comes from LAMP land.  There's a server.  The server stores and runs an application.  The application connects to a database that's (normally) on the same server.  

So with Prisma, we have a cluster (server) that stores and runs a service (application) and connects to a database (RDS).  If that's right, I'm fine so far. 

But it gets goofy for me in the operation and management.  For instance, services must not "live" on a cluster because clusters can be torn down and spun back up with the same service.  And services (applications, in my world) connect to the database, so why does the cluster need to know about the database?  Why can't I simply connect the service directly to RDS?

Obviously I'm very confused, and the problem with confusion is unconscious incompetence -- I'm not sure what questions I should be asking.  I wish I could frame this better than a stream of consciousness, but, I'm not the dumbest bunny on the block, so I suspect if I have these questions, more of the same are sure to follow.  😆

**Comment by johannpinson** [comment]
Hey @nikolasburk !

After talking with @marktani, I would like to know what will be the behavior for "Workspace"?
It will only be used to separate service into different "account/group/team" for example or also separate cluster?

Thanks,

**Comment by marktani** [comment]
We added FAQs here: https://www.prismagraphql.com/docs/faq/prisma-cloud-fae2ooth2u#what-is-a-workspace

Does that cover your questions? (or non-questions in the case of @LawJolla 😄)

**Comment by LawJolla** [comment]
Made a ton of sense, great job!

The other thing that helped me, for whatever reason, was connecting to my RDS DB with Sequel Pro and seeing my two stages, deployed to the same cluster, as two databases (schemas in Postgres land) on my one RDS instance.

**Comment by marktani** [comment]
Yup agreed, that helps a lot to understand what's going on 🙂We could add more resources about that aspect.

Closing this for now, thanks a lot for your feedback everyone 🙌
