### ISSUE TITLE
Opening dashboard of a service redirects to login page

### ISSUE THREAD

**Issue by d0ct0r4r6a-skleem** [graphcool/prisma-cloud-feedback#110]
# Bug Report

**Current behaviour**

Opening the dashboard of a service redirects to login page after a couple of seconds. Before redirecting, the error notification as reported in #107 appears for a brief period. User is still logged in.

**Reproduction**

1. Login to Prisma console
2. Click a service
3. Service dashboard will appear only for a few seconds
4. Redirected to login page

**Expected behaviour?**

Service dashboard page persists and user can see other features e.g. Deployment History, Data Browsers.

**Comment by marktani** [comment]
Thanks a lot for your report, @d0ct0r4r6a-skleem. We are looking into this right now.

**Comment by marktani** [comment]
We deployed a fix for this problem, @d0ct0r4r6a-skleem. Please let me know if you are still observing unexpected behaviour.

**Comment by d0ct0r4r6a-skleem** [comment]
Yes, the redirection stopped. Thank you for the fix.
