### ISSUE TITLE
Upgrade cluster version from console

### ISSUE THREAD

**Issue by gentle-noah** [graphcool/prisma-cloud-feedback#114]
It would be great to be able to upgrade my clusters to the next version (ie. 1.4.1 => 1.4.2) from the console

**Comment by gentle-noah** [comment]
![screen shot 2018-03-26 at 11 37 15 am](https://user-images.githubusercontent.com/4295346/37916542-141976de-30ea-11e8-8bfc-3b81f0c6c893.png)
It could easily live in this cluster settings menu

**Comment by marktani** [comment]
Thanks a lot for your suggestion, @gentle-noah! We'll add this feature soon. Please subscribe to feature request #33 to stay on track with our progress here :slightly_smiling_face:
