### ISSUE TITLE
Cannot create new cluster with the name of the deleted one

### ISSUE THREAD

**Issue by maticzav** [graphcool/prisma-cloud-feedback#118]
It seems like it's impossible to create a new cluster which holds the same name as any cluster before had - even if you have deleted the old clusters. 

Example:
 1. I create a cluster `abc`.
 2. I need to change some settings in `abc`, that's why I delete `abc` cluster.
 3. I cannot create a new cluster named `abc` because I already named another cluster `abc`.

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/38093565-a5201df8-336b-11e8-9a74-42ab16e7b709.png)

This is the error message that appears in step 3 from above.

**Comment by timsuchanek** [comment]
Thanks for reporting @maticzav. We just deployed a fix, so I'm closing this.
