### ISSUE TITLE
Provisioning Clutser Time and Deleting Cluster Time

### ISSUE THREAD

**Issue by dsoraluz-carecloud** [graphcool/prisma-cloud-feedback#130]
<img width="1114" alt="screen shot 2018-04-06 at 4 22 17 pm" src="https://user-images.githubusercontent.com/35734880/38445143-3e44239e-39c0-11e8-9fc9-f7e89141ddf8.png">
When attempting to create or delete a new cluster the status stays on "Provisioning" or "Deleting" for more than 10 minutes. It is going on more than 30 min as of the time of this writing.

**Comment by dsoraluz-carecloud** [comment]
<img width="1114" alt="screen shot 2018-04-06 at 4 22 17 pm" src="https://user-images.githubusercontent.com/35734880/38445136-36bc9dd6-39c0-11e8-9eb2-1e497230a157.png">

**Comment by marktani** [comment]
Thanks @dsoraluz-carecloud. Rarely it can happen that deletion or provisioning requests are not correctly finished. In such a case, please reach out to `support@prisma.io`, including your workspace slug and cluster name.
