### ISSUE TITLE
Upgrading to 1.6.2 or 1.6.3 doesn't seem to work

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#134]

**Comment by ntziolis** [comment]
My current cluster version is 1.6.0 and i cannot upgrade to any above. Issue doesn't seem to be limited to coming from 1.6.2

**Comment by marktani** [comment]
This has been fixed a while ago 🙂
If you still experience issues with this, please reach out to `support@prisma.io` or use the chat in the Prisma Console.
