### ISSUE TITLE
Unable to update private cluster to v1.7.1

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#136]
@yoorw commented on [Wed Apr 25 2018](https://github.com/graphcool/prisma/issues/2274)

# Bug Report

**Current behavior**
Using Prisma Console, private cluster does not update to Prisma v1.7.1.
Menu is displayed allowing to select upgrade from v1.6.3 to 1.7.1.
Popup is displayed stating "Upgrade will be done in about 10min." (see attached image)
However the cluster version stays at v1.6.3.

**Reproduction**
Reproduces 100% using Prisma Console. 

**Expected behavior?**
Expected cluster to update to v1.7.1.
Was previously able to update from v1.5.1 to v1.6.3 using the same method. 

![upgradecluster popup](https://user-images.githubusercontent.com/37107949/39263534-17d57c7c-4888-11e8-8f92-efa122062646.jpg)

**Comment by roycclu** [comment]
Hi @marktani 
We've been active graphcool users. But frankly the migration to prisma has been anything but smooth. 
I understood there was some bugs in the initial launch. 

But releasing a significant update going from v1.6 -> v1.7, without first checking if the upgrade function even works on the console seems precarious. 
Did you guys do internal testing, how did this one slip?
How can we rely on your platform for production environment?

We were gonna use prisma to power our soon-to-be production app. But reliability is a bit clouded right now.

**Comment by marktani** [comment]
Hey @roycclu, I'm so sorry about the inconvenience.

Prisma is following a strict bi-weekly release cadence. We are currently finishing the required adjustments to the upgrade process in Prisma Console to allow for upgrades to `1.7.1`. This will be finished shortly!

I understand your frustration, and will let you know once it is possible to do the upgrade 🙂

**Comment by yoorw** [comment]
Hello @marktani ,

Just for clarification, the clusters mentioned in here are private clusters.
Whereas the clusters mentioned in in [Issues#2277](https://github.com/graphcool/prisma/issues/2277) are the dev clusters provided by Prisma.

Overall, I guess I'm confused.
If Prisma provided an update to v1.7.1, but doesn't allow users to upgrade using the Prisma console, how are other users updating their Prisma server?

As a side note, I was following the tutorial from [howtographql](https://www.howtographql.com/graphql-js/7-subscriptions/) regarding subscriptions.
My local prisma updated automatically to v1.7.1 - without me having to provide any npm commands.
Why wouldn't the server side be auto updated?

If I'm missing anything, please let me know.
Or if there is documentation to help with this, please direct me in the right path.

Thanks,

**Comment by dpetrick** [comment]
I might want to chime in here: The cloud console **wrongfully** shows that 1.7.1 is available for upgrade, the underlying cloud management infrastructure is getting upgraded in the coming days to support the changes, but it's lagging as of now behind due to the nature of some of the new features in 1.7 requiring more work on the hosting side.

I understand the frustration and apologize, we will definitely try to avoid these mistakes in the future.

**Comment by marktani** [comment]
Thanks again for your feedback @roycclu 🙂

Upgrading Prisma servers to `1.7.x` should now work as expected.

If you still experience issues with this, please reach out to support@prisma.io or use the chat in the Prisma Console.
