### ISSUE TITLE
Cluster never showed up

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma-cloud-feedback#14]
I created a cluster but it never came up in my services list. On trying to create again, I get this error:-
<img width="335" alt="screen shot 2018-02-15 at 7 42 12 am" src="https://user-images.githubusercontent.com/746482/36297990-b2e87180-131b-11e8-96cb-5d6a6bd53045.png">

Since then I have changed my workspace slug to "divyenduz" but this issue is not related to that as I did that after 24+ hours of creating the cluster.

**Comment by timsuchanek** [comment]
Thanks for reporting @divyenduz ! Is this already solved? I couldn't find the cluster provisioning request anymore

**Comment by divyenduz** [comment]
Nope. I still see only the shared clusters. Should I try and create a cloud cluster again?

**Comment by timsuchanek** [comment]
Yes, please try to create a cluster again

**Comment by divyenduz** [comment]
Tried, I am able to reach the provisioning state. This issue is resolved on my end and can be closed. Please keep it around if you want to solidify something. 

Thanks!

**Comment by marktani** [comment]
Thanks @divyenduz, you can now create as many clusters as you want, and we made that process much faster and robust 🙂
