### ISSUE TITLE
Invalid default workspace name if email as a dot

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma-cloud-feedback#15]
By default, my workspace name was "divyendu.z" then I changed it to "divyenduz" but I couldn't change it back to "divyendu.z" (yes, monkey testing) with UI stating that this is invalid. 

It should not create the workspace name with a "." if it is invalid.

**Comment by timsuchanek** [comment]
Workspaces no longer create the dot in the name. Thanks for reporting @divyenduz !
