### ISSUE TITLE
Add name of cluster to switcher between services

### ISSUE THREAD

**Issue by Huvik** [graphcool/prisma-cloud-feedback#2]
When i deploy same service with same name + stage to different clusters. (Stupid thing to do, but wanted to test it.) You see in switcher same stuff:
![](https://i.imgur.com/HLdLvX0.png)

**Comment by schickling** [comment]
In the ambiguous cases I suggest adding the cluster name in parentheses after the service/stage?

Example:

```
justsystem / dev (prod-eu)
justsystem / dev (prod-us)
othersystem / dev
```

What do you think @Huvik @timsuchanek @marktani?

**Comment by Huvik** [comment]
Yea, that looks solid

**Comment by marktani** [comment]
Maybe we can even have a cluster selection/filter for the shown services. Your suggestion works great for now 👍

**Comment by timsuchanek** [comment]
Thanks for bringing this up @Huvik !
I implemented the solution @schickling suggested, only showing the cluster when needed :)
