### ISSUE TITLE
Error writing result to store for query

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/prisma-cloud-feedback#20]
I got this error in the console:
![a](https://user-images.githubusercontent.com/13983663/36340439-0cfb458c-13c4-11e8-8303-900bad146e67.png)

**Comment by marktani** [comment]
When did this happen? On which view and what did you do?

**Comment by jvbianchi** [comment]
When I load the clusters route this error shows to me

**Comment by marktani** [comment]
Thanks!

**Comment by timsuchanek** [comment]
Thanks for reporting @jvbianchi ! It is fixed and a fix is deployed in 5min
