### ISSUE TITLE
DB Connection doesn't do authentication check

### ISSUE THREAD

**Issue by senorcodecat** [graphcool/prisma-cloud-feedback#26]
I had an unhandled error when attempting to start a new Prisma cluster. 

Turned out the issue was I didn't enter the correct SQL DB credentials, yet Prisma Cloud indicated the DB was authenticated and connected correctly. 

Need to add an auth check to ensure the DB is connected correctly during setup.

**Comment by timsuchanek** [comment]
Fixed :)
