### ISSUE TITLE
I deleted a cluster and it's not being removed

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#28]
The status stays on "Deleting" forever. Cluster name `nilan-eu-1`.

**Comment by gentle-noah** [comment]
Possibly related - After deleting clusters, the name of a deleted cluster is no longer available in my workspace. My assumption is that this means the cluster is not actually being deleted.

**Comment by marktani** [comment]
I was able to issue another delete request and this time it went through. If you run into a similar problem and you can't resolve it, please create another issue 🙂 

Thanks!
