### ISSUE TITLE
If DB connection is not successful, the validation messages are wrong

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#29]
![image](https://user-images.githubusercontent.com/1780597/36345444-bf4032d2-142a-11e8-8479-fef7ddb7cbd9.png)

I provided a valid host and port, but I forgot to open up access from any IP. So my connection is refused.

The error message should be "Could not connect to database" or similar instead.

**Comment by timsuchanek** [comment]
Fix by now
