### ISSUE TITLE
Cannot see the dashboard tab

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma-cloud-feedback#31]
Dashboard tab does not show up in my cluster with custom DB. Please take a look at the attached screenshot. 

<img width="1221" alt="screen shot 2018-02-18 at 4 14 20 am" src="https://user-images.githubusercontent.com/746482/36346312-5a6a0fa8-1462-11e8-8c0c-4eadf73ae9c2.png">

**Comment by marktani** [comment]
Thanks, this is Currently expected behavior

**Comment by marktani** [comment]
The dashboard view is now available 🙂
