### ISSUE TITLE
Databrowser Error: No service with name...

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/prisma-cloud-feedback#32]
When I try to access the databrowser with any service, I get this error on the console:
![q](https://user-images.githubusercontent.com/13983663/36352244-a48cbf5e-1494-11e8-9204-6bdca8a621f2.png)

The databrowser is unusable because of this error (eternal loading):
![screen shot 2018-02-18 at 10 17 24](https://user-images.githubusercontent.com/13983663/36352257-f993a724-1494-11e8-97b8-6eb99b3ea129.png)

**Comment by jvbianchi** [comment]
I tried again to access the databrowser, but this time I got this error:
![screen shot 2018-02-27 at 15 05 28](https://user-images.githubusercontent.com/13983663/36745975-e7f48ba4-1bcf-11e8-9f91-f35108c5312f.png)

The databrowser continues unusable (eternal loading).

**Comment by jvbianchi** [comment]
I tried again today, there is no error in the console. But the databrowser continues unusable this time not even the sidebar is shown, just a spinner that spins forever.
![screen shot 2018-03-01 at 10 52 11](https://user-images.githubusercontent.com/13983663/36847975-a2342f32-1d3e-11e8-8065-15c52a406d05.png)

**Comment by marktani** [comment]
Thanks for reporting @jvbianchi, I've reached out to you to discuss this further 🙂

**Comment by timsuchanek** [comment]
This should be fixed by now. If it's still an issue, please reopen.
