### ISSUE TITLE
How to upgrade cluster

### ISSUE THREAD

**Issue by Huvik** [graphcool/prisma-cloud-feedback#33]
How to upgrade private cluster to new versions?

**Comment by marktani** [comment]
Hey @Huvik, thanks for bringing this up!

We'll soon add a feature to the Console that let's you upgrade the version of your cluster.

**Comment by Aubron** [comment]
Are there plans to update the static version until we have a manual upgrade option?

Currently new clusters are still stuck running 1.3.2

**Comment by marktani** [comment]
Hey @Aubron, we upgraded all clusters to `1.3.5` in the meanwhile. As we plan to roll out this feature soon, we will not upgrade clusters further.

**Comment by marktani** [comment]
_Upgrading_ clusters is now supported. Click the cogwheel for a cluster in the cluster view to activate it.

Note that _downgrading_ is also available in the UI, but seems to not work for all clusters. We're investigating this at the moment.

**Comment by Huvik** [comment]
I tried to upgrade a cluster from `1.5.1` to `1.5.2` and after 1 hour i am still on same version i am trying it again if it got stuck somehow

**Comment by gentle-noah** [comment]
I can not upgrade my clusters, still. I attempted the other day from 1.5.1 => 1.5.3 and I am trying again today from 1.5.1 => 1.6.0

**Comment by marktani** [comment]
We identified the problem, and will roll out a fix soon 🙂

**Comment by marktani** [comment]
This should now work for everyone. Please let me know if that's not the case 🙂

**Comment by marktani** [comment]
Note that this doesn't apply to servers hosted using one of the integrations (for example Heroku integration). You have to upgrade those manually as of today.
