### ISSUE TITLE
Non-authenticated routes

### ISSUE THREAD

**Issue by DevanB** [graphcool/prisma-cloud-feedback#34]
I noticed the other day that I was able to copy/paste an internal url (https://app.prisma.sh/devan-beitel-426772/account) for instance into another browser session and navigate to it. I also then noticed you can go to something like this: https://app.prisma.sh/something-dumb-here/account and not be redirected to login. Perhaps some internal routes aren't setup as authenticated routes yet?

**Comment by DevanB** [comment]
Correct :)

**Comment by timsuchanek** [comment]
Fixed :)
