### ISSUE TITLE
Hostname/IP doesn't match certificate's 

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma-cloud-feedback#35]
Graphcool is aware of this error, but for the benefit of those seeing it, I filed the issue.

On `prisma deploy` to a private cluster, it returns...

```
Creating stage dev for service wk_v2_server !
 ▸    request to https://[your-cluster].prisma.sh/cluster failed, reason: Hostname/IP doesn't match certificate's
 ▸    altnames: "Host: [your-cluster].prisma.sh. is not in the cert's altnames: DNS:*.prisma.sh"
```

**Comment by marktani** [comment]
Thanks @LawJolla for reporting it!
We'll likely roll out a fix for this tomorrow. It will require a small adjustment on your end, as the URL structure for clusters will change 🙂 

I will provide more information soon.

**Comment by gentle-noah** [comment]
Thanks for hoping on this so quickly @marktani  :)

**Comment by maxdarque** [comment]
Is this related to [issue #10](https://github.com/graphcool/prisma-cloud-feedback/issues/10)?

I had this error before I saw the `Did you provide the right port?` error

**Comment by gentle-noah** [comment]
I was receiving the `port` error mentioned by @maxdarque after running into initial certificate issue outlined in this ticket. I have done the following (sorry not 100% issue specific, but trying to outline repro steps and where the journey took me):

1. Destroyed my cluster
2. Updated to prisma 1.3.0-beta.5
3. Built a new cluster and got stuck here for 42 minutes:
<img width="816" alt="screen shot 2018-02-21 at 9 11 41 am" src="https://user-images.githubusercontent.com/4295346/36494590-48e303f2-16e7-11e8-9352-45d9f8d5cdd0.png">
4. Refreshed the page and got stuck here:
<img width="1026" alt="screen shot 2018-02-21 at 9 12 40 am" src="https://user-images.githubusercontent.com/4295346/36494622-6800abfe-16e7-11e8-90aa-1dc9ce8cf101.png">

**Comment by marktani** [comment]
Thanks, we'll take a look into your specific issue soon @gentle-noah! 🙂

**Comment by marktani** [comment]
This is now fixed, and the cluster endpoints have been adjusted as follows:

Previous endpoint:
`https://<cluster>.<workspace>.prisma.sh/<service>/<stage>`

New endpoint:
`https://<cluster>_<workspace>.prisma.sh/<service>/<stage>`

Please adjust the endpoints in your applications accordingly 🙂

**Comment by marktani** [comment]
@gentle-noah let's continue the discussion here #39
