### ISSUE TITLE
Workspace select menu displaying incorrect information

### ISSUE THREAD

**Issue by gentle-noah** [graphcool/prisma-cloud-feedback#36]
I have two workspaces:

1. Called MarketMuse with the slug `marketmuse`
2. Called Personal with the slug `noah`

When viewing the workplace select menu from MarketMuse the options display correctly:
<img width="297" alt="screen shot 2018-02-20 at 4 15 24 pm" src="https://user-images.githubusercontent.com/4295346/36456605-8462a56e-165a-11e8-8f9e-68fb340b0e33.png">

When viewing the workplace select menu from my space named Personal with the slug `noah` I get the following options:
<img width="291" alt="screen shot 2018-02-20 at 4 15 18 pm" src="https://user-images.githubusercontent.com/4295346/36456630-99db3abe-165a-11e8-9269-ac7afe56337a.png">

**Comment by timsuchanek** [comment]
Thanks, it now always shows the real workspace name
