### ISSUE TITLE
Create new cluster Form - Please provide a valid port

### ISSUE THREAD

**Issue by maxdarque** [graphcool/prisma-cloud-feedback#37]
**What happened**
Using Prisma Cloud, I created a new workspace and am creating a new cluster using the 'Create new cluster' Form.

I entered 3306 into the Port section and clicked on Test connection. It gave an error saying `Please provide a valid port`. No matter what number I enter I get this error.

**Expected behaviour**
Form should accept a port number

**Comment by maxdarque** [comment]
Same thing happens in my personal workspace

**Comment by marktani** [comment]
I believe that, currently, this error message is displayed if there are _any_ problems connecting to your cluster.

Please double check the endpoint, port, username and password of your database, and also check if it is publically accessible. You can do this using this command:

```sh
nc -zv <DB host> <DB port>
```

For example

```sh
nc -zv prisma-mariadb.cnvikgkukrci.eu-west-1.rds.amazonaws.com 3306
```

If the connection succeeds, this is the output (returns <1 second):

```sh
found 0 associations
found 1 connections:
     1: flags=82<CONNECTED,PREFERRED>
        outif en0
        src 192.168.178.48 port 55861
        dst 54.72.207.181 port 3306
        rank info not available
        TCP aux info available

Connection to prisma-mariadb.cnvikgkukrci.eu-west-1.rds.amazonaws.com port 3306 [tcp/mysql] succeeded!
```

Otherwise, the connection times out after a while.

**Comment by timsuchanek** [comment]
@marktani the error is appearing under the `port` input, it's unrelated to the connection itself.
I published a fix which is deploying right now

**Comment by timsuchanek** [comment]
This should be fixed by now. Can you give it another try @maxdarque ?

**Comment by maxdarque** [comment]
Thanks @timsuchanek I can now test the connection.

It sends the `TestConnection` mutation but I get the following error:
`{"data":null,"errors":[{"message":"connect ETIMEDOUT","locations":[{"line":2,"column":3}],"path":["testConnection"]}]}`

Not sure if it's related at all. I ran `nc` against the server and it returned the samething as Nilan's post above

**Comment by marktani** [comment]
Did you double check that the username/pw combination is correct?

**Comment by maxdarque** [comment]
I checked the pwd in the console where it's in clear text and it's correct. And I reset the pwd on my db just to be sure. It still is showing the same error

**Comment by marktani** [comment]
@maxdarque I had the same problem just now and could resolve it by hard-reloading. That is CMD-Shift-R on Mac.

**Comment by maxdarque** [comment]
@marktani still getting the same issue. Also seeing this if I use the docker image prisma:1.3-beta.

I can connect to my db via command line using the mysql client:

`mysql -u {username} -p{password} -h {aws.address} {DB name}`

**Comment by maxdarque** [comment]
When I try to create a cluster on Prisma Cloud using the form. I cannot successfully `Test connection`. It responds with the following:

```{"data":null,"errors":[{"message":"connect ETIMEDOUT","locations":[{"line":2,"column":3}],"path":["testConnection"]}]}```

So with that I've tried to run Prisma locally to debug. I'm running Prisma in Docker and successfully connecting to the db before it times out. Here's a link to my [docker-compose.yml](https://github.com/maxdarque/prisma-docker/blob/master/docker-compose.yml).

If I leave `SQL_INTERNAL_DATABASE` blank in the docker-compose.yml file I get the following error

```
meep:prisma-docker Max$ docker-compose up
Creating network "prismadocker_default" with the default driver
Creating prisma ... done
Attaching to prisma
prisma    | Listening for transport dt_socket at address: 8000
prisma    | Obtaining exclusive agent lock...
prisma    | Initializing workers...
prisma    | Successfully started 1 workers.
prisma    | Server running on :4466
prisma    | Version is up to date.
prisma    | Fatal error during deployment worker initialization: java.sql.SQLTransientConnectionException: internal - Connection is not available, request timed out after 5000ms.
prisma exited with code 255
```

Is this connected to the timeout error?

**Comment by maxdarque** [comment]
@marktani Is it worth opening the above in a separate issue?

**Comment by maxdarque** [comment]
My fault - I had recreated a new db instance and had forgotten to add the `Custom TCP Rule` rules per the end of this guide: 

https://gist.github.com/marktani/8631cb9c63d0973bcdd8bff19d6162c2

Should hopefully be able to close this now :)

**Comment by marktani** [comment]
Thanks @maxdarque!
