### ISSUE TITLE
Provisioning status is not updated for errors

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#39]
When provisioning my cluster, I ran into #35, so the provisioning failed.

My cluster is still saying "Provisioning" instead of "Provisioning failed":

![image](https://user-images.githubusercontent.com/1780597/36494357-1ecdb0d0-1732-11e8-8c36-1e0d196af0f4.png)

**Comment by gentle-noah** [comment]
I believe I am in this state as well:
<img width="1026" alt="screen shot 2018-02-21 at 9 12 40 am" src="https://user-images.githubusercontent.com/4295346/36494668-88c11fcc-16e7-11e8-9f27-53684b4d0006.png">

Got here after I got stuck in the provisioning screen for 42 minutes

**Comment by marktani** [comment]
@gentle-noah what happens when you "delete" the cluster? Click on the cogwheel to open up the delete button.

**Comment by gentle-noah** [comment]
@marktani - the cluster will not delete. I have tried many times. The request is sending if I monitor my network tab, but nothing happens.

**Comment by gentle-noah** [comment]
Side note, while monitoring my network tab, I discovered that on the cluster dashboard there is always a tiny picture of you loaded: https://static.intercomassets.com/avatars/982646/square_128/nilan-small-1485693435.png?1485693435

**Comment by marktani** [comment]
Thanks @gentle-noah, we found the problem for the cluster deletion and will fix it soon. I created #50 to track this separately. 

The image of me is loaded from our Intercom integration! Good to know I'm present in everyone's browser 😄

**Comment by gentle-noah** [comment]
Thanks for the update @marktani :)

**Comment by timsuchanek** [comment]
This is fixed by now - cluster creations are marked as "FAILED" in the UI.
