### ISSUE TITLE
Delete services from within the Console

### ISSUE THREAD

**Issue by fabien0102** [graphcool/prisma-cloud-feedback#41]
I don't have any button to delete a service.

**Comment by gentle-noah** [comment]
Definitely related to [#39](https://github.com/graphcool/prisma-cloud-feedback/issues/39)

**Comment by marktani** [comment]
Thanks @fabien0102 and @gentle-noah, I created a separate bug report for deleting clusters here: #50.

Adding a delete service function to the Console is a great idea!

**Comment by marktani** [comment]
This is now implemented 🙂
