### ISSUE TITLE
Create node popup doesn't close

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#43]
![image](https://user-images.githubusercontent.com/1780597/36534318-805b36b2-17c6-11e8-8175-2332ef802050.png)

Clicking "Create Node" creates the node, but doesn't close the popup.
Is this intended?

**Comment by timsuchanek** [comment]
Yes, this is intended in order to have a better workflow when creating multiple nodes.
Reopen if you consider this as an issue.
