### ISSUE TITLE
GraphQL error: Please add billing information before creating a cluster

### ISSUE THREAD

**Issue by dbuarque** [graphcool/prisma-cloud-feedback#49]
GraphQL error: Please add billing information before creating a cluster.

<img width="443" alt="screen shot 2018-02-23 at 11 20 19" src="https://user-images.githubusercontent.com/559571/36599657-dd1e355c-188e-11e8-9228-8da707da328f.png">

**Comment by timsuchanek** [comment]
Thanks for reporting @dbuarque, do you already see the credit card input? If not, please try `CMD+SHIFT+R` for hard reload

**Comment by marktani** [comment]
Thanks @dbuarque for confirming this fix 🙂
