### ISSUE TITLE
Data Browser and Playground Inop

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma-cloud-feedback#5]
I'm not sure if this is supposed to be working yet or not, or if I just have a bad configuration...

`/databrowser` just spins and 

`Playground` under `Services` links to a mistyped domain.  `https://us1.prima.sh`

**Comment by LawJolla** [comment]
Both now worked... fixed on my end!

**Comment by timsuchanek** [comment]
Perfect!
