### ISSUE TITLE
Incorrect service count

### ISSUE THREAD

**Issue by gentle-noah** [graphcool/prisma-cloud-feedback#52]
I only have one service but get a count of 3 👻 

<img width="468" alt="screen shot 2018-02-23 at 1 30 09 pm" src="https://user-images.githubusercontent.com/4295346/36617803-b805585e-189d-11e8-9f8e-b83ddffaf948.png">

**Comment by marktani** [comment]
For me it's 9 deployed vs. 10 displayed services.

**Comment by marktani** [comment]
This should be fixed by now :slightly_smiling_face: Let me know if you're still experiencing problems.
