### ISSUE TITLE
Improve test connection feature

### ISSUE THREAD

**Issue by ciocan** [graphcool/prisma-cloud-feedback#55]
I have filled the form with all mysql params but the button for testing connection does nothing.

**Comment by maxdarque** [comment]
@ciocan what does it say in console under network response? Have you checked your security group settings on AWS RDS to allow access to the 3306 port?

**Comment by ciocan** [comment]
does not say anything in the console. 
The mysql server is visible from outside,  I can connect to it from my local machine with mysql command.

**Comment by maxdarque** [comment]
Just checking, did you add the `Custom TCP Rule` inbound rule on port 3306 with source 0.0.0.0/0,::/0

Like at the very end of the tutorial https://gist.github.com/marktani/8631cb9c63d0973bcdd8bff19d6162c2

**Comment by ciocan** [comment]
that was the issue. Thanks.
Better to put a warning/error message and eventually a link to the gist doc

**Comment by marktani** [comment]
This is fixed by now :slightly_smiling_face:
