### ISSUE TITLE
Cannot access workspace/ dashboard

### ISSUE THREAD

**Issue by PatrickStrz** [graphcool/prisma-cloud-feedback#58]
I cannot access my prisma workspace, 
Steps I took:
1. run `prisma login` and the browser window opens with https://app.prisma.sh/cli-auth
2. click grant permission
3. remove the end of the url ( https://app.prisma.sh) and hit enter.

result: I get redirected back to the authentication page

When I add my workspace name at the end   https://app.prisma.sh/patrick-strzelec-1
I can see my workspace for a second and then I get redirected back to https://app.prisma.sh/cli-auth

**Comment by kuldar** [comment]
I'm getting the same results when signing up through Prisma Console. I'm pretty sure that you need to be invited to Prisma Cloud to be able to see and use the actual web UI, though. 👉https://blog.graph.cool/prisma-cloud-preview-invite-only-c251bebf5670

I might be wrong though.
