### ISSUE TITLE
Cog wheel for dev clusters shouldn't display option for deletion

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma-cloud-feedback#6]
The settings `cog wheel` menu shouldn't face the user with the option to `Delete cluster`. :)

![screenshot from 2018-02-15 18-31-13](https://user-images.githubusercontent.com/224910/36271314-88f04648-127e-11e8-9d0d-f17c31b5b749.jpg)

**Comment by schickling** [comment]
We'll soon move this on to a subpage, @akoenig! Thanks for bringing this up!

**Comment by akoenig** [comment]
Sure, you're very welcome :)

**Comment by marktani** [comment]
The cog wheel got removed 🙂
