### ISSUE TITLE
non-breaking error on graphql prepare

### ISSUE THREAD

**Issue by blaneyneil** [graphcool/prisma-cloud-feedback#64]
from a "prisma init" call, the output is showing:

SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at /home/neil/web/prisma2/.install/node_modules/graphql-boilerplate-install/src/prisma.ts:18:23
    at <anonymous>
✖ 
TypeError: Cannot read property 'workspace' of undefined
    at module.exports (/home/neil/web/prisma2/.install/index.js:22:24)
    at <anonymous>

but my above 'prisma2' service was actually created and showing in the services list.

**Comment by blaneyneil** [comment]
should note that it's the latest version of prisma - 1.3.0

**Comment by marktani** [comment]
Which boilerplate did you install?

**Comment by blaneyneil** [comment]
TS advanced (w/ auth)

**Comment by marktani** [comment]
Thanks @blaneyneil!

That error occurs if you have two different versions of `graphql` in your entire dependency tree.
Could you upgrade your dependencies and dev dependencies in `package.json` to the following:

```json
  "dependencies": {
    "bcryptjs": "2.4.3",
    "graphql-yoga": "1.4.3",
    "jsonwebtoken": "8.2.0",
    "prisma-binding": "1.5.16"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "dotenv-cli": "1.4.0",
    "graphql-cli": "2.15.8",
    "nodemon": "1.17.1",
    "npm-run-all": "4.1.2",
    "prisma": "1.3.3",
    "rimraf": "2.6.2",
    "ts-node": "4.1.0",
    "typescript": "2.7.2"
  }
```

In particular the versions for `graphql-yoga`, `prisma-binding`, `prisma` and `graphql-cli`.

Then `rm -rf node_modules yarn.lock` and `npm install` or `yarn`.

I copied the dependencies from [here](https://github.com/graphql-boilerplates/typescript-graphql-server/blob/c1ffe6899abc0f6a34c3306bf5161ccd3175de44/advanced/package.json).

**Comment by marktani** [comment]
I am closing the issue, as it seems fixed from my side :slightly_smiling_face:
