### ISSUE TITLE
Service dashboard not opening for deleted services

### ISSUE THREAD

**Issue by maxdarque** [graphcool/prisma-cloud-feedback#69]
**Issue**
My service dashboard is not opening for `up-server-example` on `prisma-eu1`.  There is a spinning loading wheel and it never opens. I can't remember but I might have deleted the service a while back so the link in my services page might be a remnant.

https://app.prisma.sh/maxdarque/services/prisma-eu1/up-server-example/dev/dashboard

**Comment by marktani** [comment]
This sounds similar to #32. I'll look into a reproduction soon.

**Comment by marktani** [comment]
I can confirm this problem. To reproduce:

* Deploy a new service to a private cluster using `prisma deploy`.
* Delete that service using `prisma delete`.
* The service is still listed in the "Services" view.
* Opening the service results in the described behaviour in the original post.

I have not tested with a development cluster, but it should be the same.

**Comment by marktani** [comment]
For some others, this error message is returned when deleting services in the Console:

![screen shot 2018-03-05 at 15 48 51 2](https://user-images.githubusercontent.com/1780597/36982916-5b651d40-2091-11e8-8d91-9b7ef29ad0ef.png)

**Comment by marktani** [comment]
The source of the problem is now resolved :slightly_smiling_face: Please reach out from the chat in your Console if you still see lingering services in your list.
