### ISSUE TITLE
Deployment won't end

### ISSUE THREAD

**Issue by jhalvorson** [graphcool/prisma-cloud-feedback#70]
hey, I’ve been experiencing this issue for the past day or two and can’t see what’s up. When I run `prisma deploy` to prisma cloud I get this:

```
Deploying` service `XXX` to stage `dev` on cluster `XXX` 1.3s

Changes:

  Class (Type)
  + Created field `lowerTitle` of type `String!`

  User (Type)
  ~ Updated field `avatar`

  FileToUser (Relation)
  + Created relation between File and User

Applying changes (12/3) ⡿
```

It just sits there spinning until I kill it, never ends.

However, when I view my deployment history on app.prisma.sh I see that it looks like it worked:

```
Jamie added 1 field, updated 1 field, added 1 relation.
4 minutes ago
```

But when I view the Data Browser I can’t see my new fields. Local stuff all works fine, just deployments to prisma cloud aren’t working for me.

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma #2011](https://github.com/graphcool/prisma/issues/2011) via [**ZenHub**](https://www.zenhub.com/)
