### ISSUE TITLE
A prisma deploy tries to find workspace "*" and fails immediately

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma-cloud-feedback#8]
After creating a cluster on Prisma Cloud, performing a `prisma login` and trying to deploy my service via `prisma deploy`, I receive the following error response:

```json
{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "No cluster could be found for workspace '*' and cluster '<cluster-name>'",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ]
    }
  ],
  "status": 200
}
```

**Comment by marktani** [comment]
Hey @akoenig, what's your `prisma version`?

**Comment by akoenig** [comment]
👋 @nilan – My version is `prisma/1.3.0-beta.1 (darwin-x64) node-v8.9.1`

**Comment by marktani** [comment]
This turned out to be caused when providing an invalid vallue for the `cluster` property in `prisma.yml`.

It needs to look like this: `<workspace>/<cluster>`.
We will improve the error handling/message in this case, thanks for bringing this up @akoenig!

**Comment by timsuchanek** [comment]
Thanks for reporting this! We added better error handling and will add a section to the faq :+1:

**Comment by timsuchanek** [comment]
For anyone who is getting this error: You need to provide the workspace slug in front of the cluster in the `prisma.yml`.
So instead of `cluster: my-cluster` you say `cluster: my-workspace/my-cluster`
