### ISSUE TITLE
Can't delete service because of name validation

### ISSUE THREAD

**Issue by KATT** [graphcool/prisma-cloud-feedback#86]
<img width="729" alt="screen shot 2018-03-08 at 13 51 37" src="https://user-images.githubusercontent.com/459267/37154427-e5177f0e-22d7-11e8-85f6-c0b4b40da35b.png">

**Comment by marktani** [comment]
Thanks for the report, @KATT! We're currently investigating the underlying cause of this :slightly_smiling_face:

**Comment by timsuchanek** [comment]
This should be fixed by now :) Please reopen if it's still an issue.
