### ISSUE TITLE
UI issues in "Create Cluster" form

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-cloud-feedback#9]
* It's easy to believe that the hinted port `3306` is already written, so that is often skipped
* the password hint is an ip, which is confusing
* if there is an error in _one_ input field, the validation messages for many input fields are activated
* it's "too easy" to enter an invalid name in the the cluster name input field, maybe the input could be sanitized while typing?
* while entering DB information, the message "Successfully connected to your DB" (or similar) is already shown when the entered password is wrong
* after clicking "Create Cluster", the UI to select the cluster region is still active

**Comment by timsuchanek** [comment]
All these points are now addressed, besides 
> it's "too easy" to enter an invalid name in the the cluster name input field, maybe the input could be sanitized while typing?
This already has validation, in real-time sanitizing user is rather confusing
> while entering DB information, the message "Successfully connected to your DB" (or similar) is already shown when the entered password is wrong
Is put into a separate issues
