### ISSUE TITLE
AWS Stack invalid

### ISSUE THREAD

**Issue by johannpinson** [graphcool/prisma-cloud-feedback#92]
I made so testing during the creation of a cluster and see options to use a cloudformation stack.
But it seems the mysql version is invalid =>
![capture d ecran 2018-03-09 a 16 28 38](https://user-images.githubusercontent.com/2202989/37214983-01ba9a6c-23b7-11e8-8156-0f1e358eec63.png)

The database created use the version "5.6.39"

**Comment by dpetrick** [comment]
Hi, can you please elaborate what exactly is the issue here? The version is a valid MySQL version. It's not the newest (if that is what you're referring to), but it is a working MySQL version nonetheless, which also works with Prisma.

**Comment by johannpinson** [comment]
Because in the docs, when we create the stack manually it's said to use the v5.7.* => https://www.prismagraphql.com/docs/tutorials/cluster-deployment/prisma-cloud-ua9gai4kie#2.4-specify-db-details
And aslo, in the Docker tutorial, the image used for MySQL is from the v5.7

In fact, I don't test but it may work with the v5.6.* but I found it weird to have only with this case a different version for MySQL.

**Comment by dpetrick** [comment]
Thank you for clarifying. This is a simple discrepancy between the docs and our template, which is confusing, but doesn't impact the Prisma setup. I will update the templates to use 5.7.x for consistency.

**Comment by dpetrick** [comment]
MySQL 5.7 is now in the latest templates.
