### ISSUE TITLE
Incorrect cluster for several workspace?

### ISSUE THREAD

**Issue by johannpinson** [graphcool/prisma-cloud-feedback#93]
I not sure of this issue because I can't reproduce it a lot of time.

This the step to follow that provoke my bug:

- I create a new cluster on my personal account named "prisma-aws".
  Then I see that I wanted to create it for my workspace named "toto" (as example).
- So I create a new custom cluster also named "prisma-aws"
- I run a `prisma deploy` and choose the `toto/prisma-aws` (and see it well in the `prisma.yml`)
- But it seems it selects the personal workspace (that I just was deleted)
- So I have this error:

![capture d ecran 2018-03-09 a 17 14 14](https://user-images.githubusercontent.com/2202989/37217324-825d7986-23bd-11e8-93c0-954bd1211095.png)

I didn't try to reproduce it again to avoid creating a lot of cluster and be invoiced for it 😉

**Comment by marktani** [comment]
Thanks, this looks like we're not handling personal workspace deletion correctly.

**Comment by timsuchanek** [comment]
Thanks for reporting @johannpinson ! This should be fixed by now. Please reopen if not the case!

**Comment by johannpinson** [comment]
Thanks guys!
