### ISSUE TITLE
Workspaces cannot be deleted or renamed.

### ISSUE THREAD

**Issue by RoryKelly** [graphcool/prisma-cloud-feedback#99]
If I go to setting delete workspace I cannot rename or delete my workspace. 
account email rockspinllc@gmail.com.

I have two workspaces called "curated", one I was invited to and one I created myself. I want to delete the one I created myself.

**Comment by timsuchanek** [comment]
Thanks for reporting @RoryKelly ! This should be fixed by now. Please reopen if still an issue :)

**Comment by marktani** [comment]
Workspaces can still not be renamed. Please follow along here for updates: https://github.com/graphcool/prisma-cloud-feedback/issues/119
